name: Example App

on:
  workflow_dispatch:
  push:
    branches:
      - features/*
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'webview-src/**'
      - 'webview-dist/**'
      - 'examples/todos-app/**'

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0

    - name: Build Tauri Plugin
      uses: actions-rs/cargo@v1
      with:
        command: build
      run: yarn && yarn build

    - name: Build example vue-todo application
      env:
        projectPath: examples/vue-todo
        distPath: examples/vue-todo/dist
      uses: tauri-apps/tauri-action@v0

    - name: Lint TODO application (rust and typescript)
      run: yarn lint