name: Example App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - 'webview-src/**'
      - 'webview-dist/**'
      - 'examples/todos-app/**'

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: examples/vue-todos/src-tauri

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install NPM dependencies
        run: |
          pnpm install --ignore-scripts
          cd ./examples/vue-todos/
          pnpm install --ignore-scripts

      - name: Build Example App
        run: |
          pnpm run build
          cd ./examples/vue-todos/
          pnpm run build:debug

      - name: Lint TODO application
        run: |
          cd ./examples/vue-todos/
          pnpm run lint
